spring:
  application:
    name: user-center-backend-springboot

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ytechtrade
    username: root
    password: fese3KAG

server:
  port: 8080