spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ytechtrade?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: app
    password: app123!App123
server:
  port: 8080
  servlet:
    context-path: /api
  address: 0.0.0.0
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
