spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ytechtrade
    username: app
    password: app123!App123

server:
  port: 8080
  servlet:
    context-path: /api
  address: 0.0.0.0