spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=postgres
spring.datasource.password=fese3KAG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.ytechtrade.springsecurity=DEBUG
logging.level.com.ytechtrade.onlineshoppingsystem=DEBUG

project.image=images/
image.base.url=http://192.168.0.176:8090/images
frontend.url=http://localhost:5173/

management.endpoints.web.exposure.include=health,info
management.endpoints.web.base-path=/api/actuator
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true

server.port=8090
