spring.application.name=OnlineShoppingSystem

spring.app.jwtSecret=mySecreteKey12312321456test985734testLucas2346678675734testLucas2348675734testL
spring.app.jwtExpireationMs=30000000

spring.ecom.app.jwtCookieName=springBootEcom
