# spring.datasource.url=jdbc:postgresql://onlineshopping-1.cvogygiweqey.us-east-2.rds.amazonaws.com:5432/postgres?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=postgres
# spring.datasource.password=admin!fese3KAG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.ytechtrade.springsecurity=DEBUG
logging.level.com.ytechtrade.onlineshoppingsystem=DEBUG

project.image=images/
image.base.url=http://localhost:8080/images

management.endpoints.web.exposure.include=health,info
management.endpoints.web.base-path=/api/actuator
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true

# server.port=5000
